-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Tempo de geração: 18/11/2024 às 15:29
-- Versão do servidor: 5.7.23-23
-- Versão do PHP: 8.1.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `lainites_aero`
--

--
-- Despejando dados para a tabela `courses`
--

INSERT INTO `courses` (`id`, `slug`, `active`, `title`, `aircraft_category`, `nick`, `obs`, `created_at`, `updated_at`, `updated_by`, `created_by`, `updated_because`, `deleted_at`, `deleted_because`, `deleted_by`, `term_contract`, `term_responsability`) VALUES
(1, NULL, 1, 'INSTRUTOR DE VOO - AVIÃO', 1, 'INVA', NULL, '2022-07-15 20:52:28', '2022-10-08 19:01:04', 'OSVALDO LAINI', 'OSVALDO LAINI', NULL, NULL, NULL, NULL, '<p><span style=\"font-size: 12px;\">1 - NESTE ATO ESTÁ SENDO ENTREGUE AO CANDIDATO, A CÓPIA DO REGULAMENTO DE CURSO PRETENDIDO</span><span style=\"font-size: 12px;\"><br></span></p><p><span style=\"font-size: 12px;\">2 - NO CASO DE ALUNO SER MENOR DE IDADE, SERÁ NECESSÁRIA A AUTORIZAÇÃO DOS PAIS OU RESPONSÁVEL LEGAL.</span><br></p><p><span style=\"font-size: 12px;\">TERMO DE COMPROMISSO RBHA 141.89 (d)</span><br></p><p><span style=\"font-size: 12px;\">Nos cursos teóricos para obtenção de licenças que exigem aprovação em exame de saúde nos termos do RBHA 67 ou seja, licença&nbsp;</span><span style=\"font-size: 12px;\">de piloto, mecânico de voo, comissário de voo e operador de equipamentos especiais, exigência do paragráfo (a)(1)(v) desta seção pode&nbsp;</span><span style=\"font-size: 12px;\">ser substituída por um \"Termo de Compromisso\", assinando pelo canditado, declarando estar ciente de que a obtenção dio CCF é&nbsp;</span><span style=\"font-size: 12px;\">obrigatória para início do instrução prática, que a não obtenção do mesmo por incapacidade física tem como consequência a&nbsp;</span><span style=\"font-size: 12px;\">impossibilidade de obtenção da lincença pretendida inicialmente e isentando a entidade e a ANAC de qualquer responsabilidade decorrente de uma&nbsp;</span><span style=\"font-size: 12px;\">eventual não obtenção do CCF(Port. 1177/DGAC,08/11/05; DOU 216, 10/11/05)</span></p>', '<p><span style=\"font-size: 12px;\">DECLARO PARA FINS JURIDICOS, QUE OS DADOS POR MIM FORNECIDOS, SÃO EXPRESSÃO DA VERDADE E QUE, ANTES DE PREENCHER ESTE&nbsp;</span><span style=\"font-size: 12px;\">FORMULARIO, RECEBI TODAS AS INFORMAÇÕES PERTINEMTES AO CURSO DE PP-A, CONTIDAS NO REGULAMENTO CUJA CÓPIA RECEBI NESTE ATO,&nbsp;</span><span style=\"font-size: 12px;\">DO CURSO PRETENDIDO A ESTRUTURA CURRICULAR DO CURSO E A PROGRAMAÇÃO DE SEU DESENVOLVIMENTO , AS NORMAS DICIPLINARES,&nbsp;</span><span style=\"font-size: 12px;\">OPERACIONAIS E ADMINISTRATIVAS E AINDA, AS REFERENTES AO SISTEMA DE&nbsp; AVALIAÇÃO E DE APROVAÇÃO UTILIZADO PELA ESCOLA.</span></p><p><span style=\"font-size: 12px;\">Obs.Importante. Todo aluno deverá estar em posso do CCF antes de começar a parte prática</span></p>'),
(2, NULL, 1, 'PILOTO PRIVADO - PLANADOR', 2, 'PPL', NULL, '2022-07-15 20:52:50', '2022-10-08 19:00:04', 'OSVALDO LAINI', 'OSVALDO LAINI', NULL, NULL, NULL, NULL, '<p><span style=\"font-size: 12px;\">1 - NESTE ATO ESTÁ SENDO ENTREGUE AO CANDIDATO, A CÓPIA DO REGULAMENTO DE CURSO PRETENDIDO</span><span style=\"font-size: 12px;\"><br></span></p><p><span style=\"font-size: 12px;\">2 - NO CASO DE ALUNO SER MENOR DE IDADE, SERÁ NECESSÁRIA A AUTORIZAÇÃO DOS PAIS OU RESPONSÁVEL LEGAL.</span><br></p><p><span style=\"font-size: 12px;\">TERMO DE COMPROMISSO RBHA 141.89 (d)</span><br></p><p><span style=\"font-size: 12px;\">Nos cursos teóricos para obtenção de licenças que exigem aprovação em exame de saúde nos termos do RBHA 67 ou seja, licença&nbsp;</span><span style=\"font-size: 12px;\">de piloto, mecânico de voo, comissário de voo e operador de equipamentos especiais, exigência do paragráfo (a)(1)(v) desta seção pode&nbsp;</span><span style=\"font-size: 12px;\">ser substituída por um \"Termo de Compromisso\", assinando pelo canditado, declarando estar ciente de que a obtenção dio CCF é&nbsp;</span><span style=\"font-size: 12px;\">obrigatória para início do instrução prática, que a não obtenção do mesmo por incapacidade física tem como consequência a&nbsp;</span><span style=\"font-size: 12px;\">impossibilidade de obtenção da lincença pretendida inicialmente e isentando a entidade e a ANAC de qualquer responsabilidade decorrente de uma&nbsp;</span><span style=\"font-size: 12px;\">eventual não obtenção do CCF(Port. 1177/DGAC,08/11/05; DOU 216, 10/11/05)</span></p>', '<p><span style=\"font-size: 12px;\">DECLARO PARA FINS JURIDICOS, QUE OS DADOS POR MIM FORNECIDOS, SÃO EXPRESSÃO DA VERDADE E QUE, ANTES DE PREENCHER ESTE&nbsp;</span><span style=\"font-size: 12px;\">FORMULARIO, RECEBI TODAS AS INFORMAÇÕES PERTINEMTES AO CURSO DE PP-A, CONTIDAS NO REGULAMENTO CUJA CÓPIA RECEBI NESTE ATO,&nbsp;</span><span style=\"font-size: 12px;\">DO CURSO PRETENDIDO A ESTRUTURA CURRICULAR DO CURSO E A PROGRAMAÇÃO DE SEU DESENVOLVIMENTO , AS NORMAS DICIPLINARES,&nbsp;</span><span style=\"font-size: 12px;\">OPERACIONAIS E ADMINISTRATIVAS E AINDA, AS REFERENTES AO SISTEMA DE&nbsp; AVALIAÇÃO E DE APROVAÇÃO UTILIZADO PELA ESCOLA.</span></p><p><span style=\"font-size: 12px;\">Obs.Importante. Todo aluno deverá estar em posso do CCF antes de começar a parte prática</span></p>'),
(3, NULL, 1, 'PILOTO PRIVADO - AVIÃO', 1, 'PPA', NULL, '2022-07-15 20:53:09', '2022-10-08 19:01:21', 'OSVALDO LAINI', 'OSVALDO LAINI', NULL, NULL, NULL, NULL, '<p><span style=\"font-size: 12px;\">1 - NESTE ATO ESTÁ SENDO ENTREGUE AO CANDIDATO, A CÓPIA DO REGULAMENTO DE CURSO PRETENDIDO</span><span style=\"font-size: 12px;\"><br></span></p><p><span style=\"font-size: 12px;\">2 - NO CASO DE ALUNO SER MENOR DE IDADE, SERÁ NECESSÁRIA A AUTORIZAÇÃO DOS PAIS OU RESPONSÁVEL LEGAL.</span><br></p><p><span style=\"font-size: 12px;\">TERMO DE COMPROMISSO RBHA 141.89 (d)</span><br></p><p><span style=\"font-size: 12px;\">Nos cursos teóricos para obtenção de licenças que exigem aprovação em exame de saúde nos termos do RBHA 67 ou seja, licença&nbsp;</span><span style=\"font-size: 12px;\">de piloto, mecânico de voo, comissário de voo e operador de equipamentos especiais, exigência do paragráfo (a)(1)(v) desta seção pode&nbsp;</span><span style=\"font-size: 12px;\">ser substituída por um \"Termo de Compromisso\", assinando pelo canditado, declarando estar ciente de que a obtenção dio CCF é&nbsp;</span><span style=\"font-size: 12px;\">obrigatória para início do instrução prática, que a não obtenção do mesmo por incapacidade física tem como consequência a&nbsp;</span><span style=\"font-size: 12px;\">impossibilidade de obtenção da lincença pretendida inicialmente e isentando a entidade e a ANAC de qualquer responsabilidade decorrente de uma&nbsp;</span><span style=\"font-size: 12px;\">eventual não obtenção do CCF(Port. 1177/DGAC,08/11/05; DOU 216, 10/11/05)</span></p>', '<p><span style=\"font-size: 12px;\">DECLARO PARA FINS JURIDICOS, QUE OS DADOS POR MIM FORNECIDOS, SÃO EXPRESSÃO DA VERDADE E QUE, ANTES DE PREENCHER ESTE&nbsp;</span><span style=\"font-size: 12px;\">FORMULARIO, RECEBI TODAS AS INFORMAÇÕES PERTINEMTES AO CURSO DE PP-A, CONTIDAS NO REGULAMENTO CUJA CÓPIA RECEBI NESTE ATO,&nbsp;</span><span style=\"font-size: 12px;\">DO CURSO PRETENDIDO A ESTRUTURA CURRICULAR DO CURSO E A PROGRAMAÇÃO DE SEU DESENVOLVIMENTO , AS NORMAS DICIPLINARES,&nbsp;</span><span style=\"font-size: 12px;\">OPERACIONAIS E ADMINISTRATIVAS E AINDA, AS REFERENTES AO SISTEMA DE&nbsp; AVALIAÇÃO E DE APROVAÇÃO UTILIZADO PELA ESCOLA.</span></p><p><span style=\"font-size: 12px;\">Obs.Importante. Todo aluno deverá estar em posso do CCF antes de começar a parte prática</span></p>'),
(4, NULL, 1, 'PILOTO COMERCIAL - AVIÃO', 1, 'PCA', NULL, '2022-08-30 15:50:02', '2022-10-08 18:58:08', 'OSVALDO LAINI', 'CHARLES GUZENSKI', NULL, NULL, NULL, NULL, '<p><span style=\"font-size: 12px;\">1 - NESTE ATO ESTÁ SENDO ENTREGUE AO CANDIDATO, A CÓPIA DO REGULAMENTO DE CURSO PRETENDIDO</span><span style=\"font-size: 12px;\"><br></span></p><p><span style=\"font-size: 12px;\">2 - NO CASO DE ALUNO SER MENOR DE IDADE, SERÁ NECESSÁRIA A AUTORIZAÇÃO DOS PAIS OU RESPONSÁVEL LEGAL.</span><br></p><p><span style=\"font-size: 12px;\">TERMO DE COMPROMISSO RBHA 141.89 (d)</span><br></p><p><span style=\"font-size: 12px;\">Nos cursos teóricos para obtenção de licenças que exigem aprovação em exame de saúde nos termos do RBHA 67 ou seja, licença&nbsp;</span><span style=\"font-size: 12px;\">de piloto, mecânico de voo, comissário de voo e operador de equipamentos especiais, exigência do paragráfo (a)(1)(v) desta seção pode&nbsp;</span><span style=\"font-size: 12px;\">ser substituída por um \"Termo de Compromisso\", assinando pelo canditado, declarando estar ciente de que a obtenção dio CCF é&nbsp;</span><span style=\"font-size: 12px;\">obrigatória para início do instrução prática, que a não obtenção do mesmo por incapacidade física tem como consequência a&nbsp;</span><span style=\"font-size: 12px;\">impossibilidade de obtenção da lincença pretendida inicialmente e isentando a entidade e a ANAC de qualquer responsabilidade decorrente de uma&nbsp;</span><span style=\"font-size: 12px;\">eventual não obtenção do CCF(Port. 1177/DGAC,08/11/05; DOU 216, 10/11/05)</span></p>', '<p><span style=\"font-size: 12px;\">DECLARO PARA FINS JURIDICOS, QUE OS DADOS POR MIM FORNECIDOS, SÃO EXPRESSÃO DA VERDADE E QUE, ANTES DE PREENCHER ESTE&nbsp;</span><span style=\"font-size: 12px;\">FORMULARIO, RECEBI TODAS AS INFORMAÇÕES PERTINEMTES AO CURSO DE PP-A, CONTIDAS NO REGULAMENTO CUJA CÓPIA RECEBI NESTE ATO,&nbsp;</span><span style=\"font-size: 12px;\">DO CURSO PRETENDIDO A ESTRUTURA CURRICULAR DO CURSO E A PROGRAMAÇÃO DE SEU DESENVOLVIMENTO , AS NORMAS DICIPLINARES,&nbsp;</span><span style=\"font-size: 12px;\">OPERACIONAIS E ADMINISTRATIVAS E AINDA, AS REFERENTES AO SISTEMA DE&nbsp; AVALIAÇÃO E DE APROVAÇÃO UTILIZADO PELA ESCOLA</span></p><p><span style=\"font-size: 12px;\">Obs.Importante. Todo aluno deverá estar em posso do CCF antes de começar a parte prática</span></p>'),
(5, NULL, 1, 'REPASSE AVIÃO', 1, 'REP/AV', NULL, '2022-09-14 01:17:47', '2022-10-15 17:48:42', 'CHARLES GUZENSKI', 'CHARLES GUZENSKI', NULL, NULL, NULL, NULL, NULL, NULL),
(6, NULL, 2, 'CHEQUE/REVALIDAÇÕES', 1, 'CQ/REVALID', NULL, '2022-09-14 01:58:49', '2022-10-15 17:21:34', NULL, 'CHARLES GUZENSKI', NULL, '2022-10-15', NULL, 'CHARLES GUZENSKI', NULL, NULL),
(7, NULL, 2, 'TRANSLADO', 1, 'TRANSLADO', NULL, '2022-09-14 02:14:26', '2022-10-14 14:17:49', NULL, 'CHARLES GUZENSKI', NULL, '2022-10-14', NULL, 'CHARLES GUZENSKI', NULL, NULL),
(8, NULL, 1, 'REVALIDAÇÃO DE HABILITAÇÕES DE PLANADOR', 2, 'REV/PLAN', NULL, '2022-10-15 15:18:35', '2022-10-15 15:23:41', 'CHARLES GUZENSKI', 'CHARLES GUZENSKI', NULL, NULL, NULL, NULL, NULL, NULL),
(9, NULL, 1, 'REVALIDAÇÃO DE HABILITAÇÕES DE AVIÃO', 1, 'REV/AV', NULL, '2022-10-15 17:10:23', '2022-10-15 17:10:23', NULL, 'CHARLES GUZENSKI', NULL, NULL, NULL, NULL, NULL, NULL),
(10, NULL, 1, 'REPASSE PLANADOR', 2, 'REP/PLAN', NULL, '2022-10-15 17:58:20', '2022-10-15 17:58:49', 'CHARLES GUZENSKI', 'CHARLES GUZENSKI', NULL, NULL, NULL, NULL, NULL, NULL),
(11, NULL, 1, 'INSTRUTOR DE VOO - PLANADOR', 2, 'INPL', NULL, '2023-12-28 16:34:20', '2023-12-28 16:34:20', NULL, 'CHARLES GUZENSKI', NULL, NULL, NULL, NULL, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
